/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sabine' at '28.06.16 14:02' with Gradle 2.14
 *
 * @author Sabine, @date 28.06.16 14:02
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
